# Generated by Django 4.0.4 on 2022-10-04 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
