# Generated by Django 4.0.4 on 2022-10-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='img',
        ),
    ]
