# Generated by Django 4.0.4 on 2022-10-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_material_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
