# Generated by Django 4.0.4 on 2022-10-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_material_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
