# Generated by Django 4.0.4 on 2022-10-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_material_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='created_at',
        ),
    ]
