# Generated by Django 4.0.4 on 2022-10-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_material_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='img',
            field=models.ImageField(default='/media/TOEFL-Study-Material_Ec4iBJ5.jpg', upload_to=''),
        ),
    ]
