# Generated by Django 4.0.4 on 2022-10-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_material_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='img',
            field=models.ImageField(default='/TOEFL-Study-Material_Ec4iBJ5.jpg', upload_to=''),
        ),
    ]
